version: '3'

services:
  db:
    image: mysql
    container_name: serverdb
    restart: always
    environment:
      - MYSQL_DATBASE=mydatabase
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - 13306:3306
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
  server-go:
    build: .
    ports:
      - 8080:9999
    depends_on:
      - db
